### ISSUE TITLE
invalid syntax for integer with base 16 in h2b

### ISSUE THREAD

**Issue by davidhelms** [virtualabs/radiobit#3]
I'm trying to use the ubit-sniffer tool
When I uflash using the following command from the readme

$ uflash -r precompiled/radiobit.hex tools/ubit-sniffer/middleware/ubit-sniffer-mw.py

If I connect to the serial port with screen, I see the following error

Traceback (most recent call last):
  File "__main__", line 98, in <module>
  File "__main__", line 28, in readhex
  File "__main__", line 37, in h2b
ValueError: invalid syntax for integer with base 16

**Comment by virtualabs** [comment]
The ubit-sniffer-mw.py is a middleware Python program for the Micro:Bit, it is intended to communicate with a CLI tool through serial, not directly with screen or minicom. 

Please use the provided ubit-sniffer.py CLI tool to interact with the Micro:Bit, once flash with the ubit-sniffer-mw.py python program (your uflash command is correct by the way !).

**Comment by crashish** [comment]
I'm seeing that "Line 37 ValueError: invalid syntax for integer with base 16" scrolls on the Micro:Bit's LED matrix during boot-up with this middleware.
